import {
  type IconNode as LucideIcon,
  X,
  Plus,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Check,
  Circle,
  Info,
  Star,
  MoreHorizontal,
  SeparatorHorizontal,
  ArrowDownNarrowWide,
  ArrowUpWideNarrow,
  Loader2,
  Trash,
  Search,
  Image,
  AlertCircle,
  FileWarning,
  Timer,
  DownloadCloud,
  UploadCloud
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  close: X,
  plus: Plus,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  check: Check,
  circle: Circle,
  info: Info,
  star: Star,
  more: MoreHorizontal,
  separator: SeparatorHorizontal,
  sortAsc: ArrowUpWideNarrow,
  sortDesc: ArrowDownNarrowWide,
  spinner: Loader2,
  trash: Trash,
  search: Search,
  image: Image,
  alert: AlertCircle,
  warning: FileWarning,
  timer: Timer,
  download: DownloadCloud,
  upload: UploadCloud,
} as const
